name: Publish Release
concurrency: production

on:
  workflow_run:
    workflows:
      - "Build Project"
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/libs
      - name: Extract Version
        id: extract_version
        run: |
          version=$(./gradlew properties -q | grep "^version: " | awk '{print $2}')
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Extract Project Name
        id: extract_project_name
        run: |
          project_name=$(./gradlew properties -q | grep "^name: " | awk '{print $2}')
          echo "PROJECT_NAME=$project_name" >> $GITHUB_ENV
      - name: Upload JAR files
        uses: actions/upload-artifact@v3
        with:
          name: kotlin-plugin
          path: build/libs/v${{ env.VERSION }}/${{ env.PROJECT_NAME }}-v${{ env.VERSION }}.jar
      - name: Create Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: '${{ env.PROJECT_NAME }} v.${{ env.VERSION }}'
          draft: false
          prerelease: false
      - name: Upload sources JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/${{ env.PROJECT_NAME }}-${{ env.VERSION }}.jar
          asset_name: ${{ env.PROJECT_NAME }}-v${{ env.VERSION }}-sources.jar
          asset_content_type: application/java-archive
      - name: Upload remapped JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/${{ env.PROJECT_NAME }}-${{ env.VERSION }}-remapped.jar
          asset_name: ${{ env.PROJECT_NAME }}-v${{ env.VERSION }}.jar
          asset_content_type: application/java-archive
